### ISSUE TITLE
Should not apply success class on returning empty observable

### ISSUE THREAD

**Issue by Atal14** [sa-bangash/ngxs-loading-plugin#1]
When I am using the call client function [ngxsSubmitLoading], if the function returns an empty observable then **success** class is applied to that element(button)

If the function returns an empty observable then no class should be applied to that element(button)

![empty observable](https://user-images.githubusercontent.com/60308751/93998417-f03e3680-fdad-11ea-9627-b86cc4bf03d5.png)

**Comment by sa-bangash** [comment]
hmm nice flow let me add it,

**Comment by sa-bangash** [comment]
you can check in a new release, the problem is resolved, and thanks for reporting

**Comment by sa-bangash** [comment]
@Atal14 kindly close the issue once you verify
