### ISSUE TITLE
Class should only applied to element(button) that was clicked

### ISSUE THREAD

**Issue by Atal14** [sa-bangash/ngxs-loading-plugin#2]
When we apply [ngxsActionWatchLoading] to multiple buttons with same action. After clicking on one button (and it's success or error) the success or error class is applied to all the buttons. 

The success/error class should be only applied to the element(button) that was clicked

![multiple buttons](https://user-images.githubusercontent.com/60308751/93999985-f03f3600-fdaf-11ea-8949-4482c4512dc1.png)

**Comment by sa-bangash** [comment]
@Atal14 you can use the [ngxsSubmitLoading]="onDelete.bind(this)" delete should return observable. by this approach my your problem resolve
