### ISSUE TITLE
Class should be removed from element after some time

### ISSUE THREAD

**Issue by Atal14** [sa-bangash/ngxs-loading-plugin#3]
When class (success/error) is applied to a element(button) it stays there until the page is refreshed

The class should be removed from the element(button) 

Possible solutions
- Remove the class from the element(button) after sometime, lets say 2 secs
- Remove the class on some changes (like when user starts typing)

![1 time](https://user-images.githubusercontent.com/60308751/94001680-4ca35500-fdb2-11ea-9115-5ac76c40e4f6.png)
Class remains even after change
![2 time](https://user-images.githubusercontent.com/60308751/94001703-54fb9000-fdb2-11ea-9985-15d8f6f4c0de.png)

**Comment by sa-bangash** [comment]
@Atal14 new version is released and you can manage by  [ngxsInValid]="(form.invalid && !form.pristine)" check out the documentation

**Comment by sa-bangash** [comment]
once you verify than close the issue
